### ISSUE TITLE
Grafikte baba tarafi gorunmuyor

### ISSUE THREAD

**Issue by yasinaydinnet** [okul101/SoyAgaci#1]
Sadece anne tarafi gorunuyor.

**Comment by gokberkhamurcu** [comment]
Bildirim için teşekkürler.

Tahmin edebileceğiniz sebeplerle uygulamayı yazarken elimizde çok fazla örnek dosya yoktu, eldekilere göre metin ayrıştırma işini yapmaya çalıştık.

Anladığımız kadarıyla e-devletten alınan çıktılarda biçimsel olarak bir standart yok, bu nedenle bazı kullanıcılarda ne yazık ki sizdeki gibi sonuçlar oluyor.

Tespit edebildiğimiz farklılıklara göre güncelleme yapıyoruz.
