### ISSUE TITLE
Üzgünüz, dosyanız okunamadı hatası alınıyor.

### ISSUE THREAD

**Issue by ghost** [okul101/SoyAgaci#2]
Hatayı veren örnek dosyanın ekran görüntüleri şu şekildedir.
![untitled](https://user-images.githubusercontent.com/3073437/36549853-dec17804-1804-11e8-8354-0386e0f458e1.png)
![untitled2](https://user-images.githubusercontent.com/3073437/36549855-df326d98-1804-11e8-8a75-ebe574b43ead.png)

Hata main.js  içerisinde processPdfAndDraw fonksiyonunun 71. satırındaki 
 `cells.push(textItems[i + j].str);` içerisinde indis değerlerinin toplamındaki sorundan kaynaklanan string değerin alınamamasından kaynaklanıyor. Bilginize.

**Comment by gokberkhamurcu** [comment]
Ayrıntılı bildirim için teşekkürler.

Tahmin edebileceğiniz sebeplerle uygulamayı yazarken elimizde çok fazla örnek dosya yoktu, eldekilere göre metin ayrıştırma işini yapmaya çalıştık.

Anladığımız kadarıyla e-devletten alınan çıktılarda biçimsel olarak bir standart yok, bu nedenle bazı kullanıcılarda ne yazık ki sizdeki gibi sonuçlarla karşılaşılıyor.

Tespit edebildiğimiz farklılıklara göre güncelleme yapıyoruz.

Elde örnek olmadan şu aşamada 71. satır için yapabildiğimiz tek şey dizi uzunluk kontrolü eklemek oldu , tekrar deneyip sonucu iletirseniz seviniriz.
