### ISSUE TITLE
Pdf Standartı

### ISSUE THREAD

**Issue by hurkanakbiyik** [okul101/SoyAgaci#3]
Aynı çalışmayı bende sizin gibi yapmaya çalışmıştım fakat alınan pdf çıktılarında bir standart yok. Tarayıcı tipi, işletim sistemi kullanılan ek uzantılar vb. sebebiyle oluşan pdf formatları ve hücre biçimleri değişiyor.

Pdf üzerinden bütün textleri satırda gruplayarak okuyup regex kullanarak bu çalışmanızı yapabilirsiniz ama çok zahmetli olacaktır. Pdf dönüştürme işiyle bayağı uğraşmıştım ve bir çıkış yolu bulamamıştım bunun bilgisini vermek istedim.

Başarılar dilerim.👍

**Comment by gokberkhamurcu** [comment]
İyi dilekleriniz için teşekkürler.

İlk yayına aldıktan sonra bize ulaşan bildirimlere göre birkaç düzeltmemiz oldu. Herhangi bir kayıt tutmadığımız için net bilgi sahibi değiliz ancak bize ulaşan pozitif tepkilerden anladığımız kadarıyla yüksek oranla dosyaları okuyabiliyoruz gibi görünüyor.
